
GET http://localhost:8080/ping
Accept: application/json
```

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "Code": "Product 2",
  "price": 100
}
```

###
GET http://localhost:8080/products
Accept: application/json
```

###
GET http://localhost:8080/products/2
Accept: application/json
```